# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: build release
      run: |
        pyinstaller.exe --onefile --noconsole --icon=icon.ico OneSidedScansMergerApp.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
    # Artifact name
        name: win-release
    # A file, directory or wildcard pattern that describes what to upload
        path: dist/OneSidedScansMergerApp.exe
    # The desired behavior if no files are found using the provided path.
        retention-days: 90

